rules:
- name: brute_force_block
  if:
    type: Brute Force
    count_greater_than: 5
  then:
  - action: firewall_block_ip
    params:
      ip_field: src_ip
  mitre:
  - T1110
- name: high_severity_malware_isolate
  if:
    type: Malware
    severity_equals: High
  then:
  - action: edr_isolate_host
    params:
      host_field: machine
  mitre:
  - T1059.001
  - T1105
